### PR TITLE
Overlays and focus options

### PR DESCRIPTION
**Pull request by CadoCat**
Added portrait overlay option and option to hide buffs on focus targets

### CODE REVIEW

**Review by Hydra-Mods — COMMENTED** [review]
I appreciate you being willing to contribute to HydraUI! For consistency in the future when creating new settings you need to create an entry in the Defaults table, not the Settings table. In Player.lua you directly added "player-overlay-alpha" to Settings, and then forgot to make a setting for the Target overlay

**Comment by Hydra-Mods** [comment]
I've added the setting for target portrait alpha, and for the focus debuffs

**Comment by CadoCat** [comment]
Thanks for this. I can see the error's I've made now. Thanks for the feedback.

**Comment by Hydra-Mods** [comment]
Right on, thank you again for the contribution!

**Pull request merged**
